services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: lk_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Кэш Redis
  redis:
    image: redis:7-alpine
    container_name: lk_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # S3-хранилище MinIO
  minio:
    image: minio/minio
    container_name: lk_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MC_HOST_local: http://${MINIO_ACCESS_KEY}:${MINIO_SECRET_KEY}@minio:9000
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Сервис для выполнения миграций
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    # Точкой входа должен быть shell.
    entrypoint: /bin/sh
    command: -c "/migrate -path /migrations/schema -database $$DATABASE_URL up"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    restart: "no"

  # Наше Go-приложение
  app:
    container_name: lk_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file: .env
    restart: unless-stopped

# Volumes для сохранения данных между перезапусками
volumes:
  postgres_data:
  redis_data:
  minio_data: